name: War
main: bukkit.tommytony.war.War
version: 0.3
commands:
#-Fallback-
  war:
    description: Prompts you to use /warhub, /zones and /zone. Can also be used as a prefix for all commands as a fallback if they are taken.
    usage: /war, /war setzone ziggy northwest, /war warhub, /war zone ziggy, etc.
  War:
    description: Same as /war. Used as fallback.
    usage: See /war.
##-Player commands-
  warzones: 
    description: Lists the warzones on the server. Each warzone is an independent TDM arena.
    usage: /warzones
  zones:
    description: Shortcut for /warzones.
    usage: /zones
  warzone:
    description: Teleports you to the specified warzone's lobby.
    usage: /warzone ziggy
  zone:
    description: Shortcut for /warzone.
    usage: /zone ziggy
  warhub:
    description: Teleports you to the warhub, if it exists. The warhub offers portals to reach each warzone on the server.
    usage: /warhub
  teams:
    description: Lists the teams in the warzone. Must be standing in zone or in its lobby.
    usage: /teams
  join:
    description: Use to change teams. Must be in zone. If in lobby, use to join a team as an alternative to walking in the team gate.
    usage: /join <diamond/iron/gold/d/i/g>
  leave:
    description: Use to leave a battle or a zone. Teleports you back to the zone lobby. Must be in a team already and inside the zone.
    usage: /leave
  team:
    description: Team chat. 
    usage: /team Leeeroooy!!!
#-Warzone maker commands-
#--Battle-related commands--
  nextbattle:
    description: War makers only. Zone blocks are restored (from memory). Teams are respawned. Just as if a team's life pool had been exhausted.
    usage: /nextbattle
#--Warzone creation commands--
  setzone:
    description: Zone makers only. Use to create and adjust the warzone outline. A zone area is defined by its Northwest and Southeast corners, up to the sky and down to adminium. When the second corner is set down correctly, the zone blocks are saved.
    usage: /setzone <northwest/southeast/nw/se>, e.g. first, /setzone ziggy se, then, /setzone ziggy northwest
  savezone:
    description: Zone makers only. Use to persist any aesthetic or practical changes made to the zone after the last save. Puts down a default lobby if there are none already. Use optional named parameters to change zone config. Must be in warzone or lobby. 
    usage: /savezone, /savezone lifepool:8 teamsize:5 maxscore:7 autoassign:on outline:off ff:on
  setzonelobby:
    description: Zone makers only. Creates or changes the position of the warzone lobby. Must be in warzone or lobby.
    usage: /setzonelobby <north/east/south/west/n/e/s/w>
  setteam:
    description: Zone makers only. Creates or moves a team spawn. The lobby is updated to reflect any new team. The only available teams are diamond, iron and gold. Must be warzone. 
    usage: /setteam <diamond/iron/gold/d/i/g>
  setmonument:
    description: Zone makers only. Creates or moves a monument. Must be in warzone.  
    usage: /setmonument <monument-name>
  resetzone:
    description: Zone makers only. Reloads zone blocks from memory by default. Reloads blocks from disk if "hard" option is added. Sends everyone back to the warzone lobby. Must be in zone or lobby. 
    usage: /resetzone, /resetzone <hard/h>
  deletezone:
    description: Zone makers only. Deletes the zone, resets all blocks. Must be in zone or lobby.  
    usage: /deletezone
  deleteteam:
    description: Zone makers only. Deletes the team. Team must exist. 
    usage: /deleteteam <d/i/g>
  deletemonument:
    description: Zone makers only. Deletes the monument. 
    usage: /deletemonument <monument-name>
  setzoneconfig:
    description: Zone makers only. Use named parameters in any order to change configuration of the zone. Does not save zone blocks like /savezone.
    usage: /setzoneconfig lifepool:8 teamsize:5 maxscore:7 autoassign:on outline:off ff:on
  zonemaker:
    description: Zone makers only. Toggles between player mode and zone maker mode. Or gives/removes access to zonemaker commands for another player. 
    usage: /zonemaker, /zonemaker <new-or-kicked-maker-name>
#--War hub--
  setwarhub:
    description: War makers only. Create or moves a West-facing wall of portals. One portal per warzone. Warzones get a portal back to the warhub.
    usage: /setwarhub
  deletewarhub:
    description: War makers only. Deletes the warhub if it exists. Resets all warzone lobbies.
    usage: /deletewarhub
#--Defaults--
  setwarconfig:
    description: War makers only. Change the default warzone configuration values.
    usage: /setwarconfig lifepool:8 teamsize:5 maxscore:7 autoassign:on outline:off ff:on
    
    
    
#Note: When you /disable War with General, all warzone blocks will be reset and artifacts will disappear. 
#      When you /enable War, all blocks will be loaded from disk and the War-related artifacts will reappear.  