name: War
version: 1.8.1 (Lee)
description: Minecraft PVP arenas (called warzones) for a fast-paced and structured PVP experience with TDM, CTF & more!
author: tommytony
website: http://war.tommytony.com
main: com.tommytony.war.War
softdepend: [Spout]
permissions:
  war.*:
    description: Full War permissions. Create and destroy warzones. Change War configuration.
    default: op
    children:
      war.admin: true
      war.zonemaker: true
      war.player: true
      war.warp: true
      war.build: true
      war.pvp: true
  war.admin:
    description: War admin rights. Create and destroy warzones. Change War configuration.
    default: false
    children:
      war.zonemaker: true
      war.player: true
      war.build: true
  war.zonemaker:
    description: Warzone maker rights. Create and edit warzones, but you can only edit a warzone if you are its author.
    default: false
    children:
      war.player: true
      war.build: true
  war.player:
    description: Lets you participate in War matches.
    default: true
  war.warp:
    description: Gives you access the /zone and /warhub commands that let you teleport to all warzones.
    default: true
  war.build:
    description: 
      Useful only after using /warcfg buildinzonesonly:true. This node circumvents the build restriction and lets you build outside warzones. 
      Give war.build to people that you consider worthy of having build rights. 
    default: false
  war.pvp:
    description: 
      Useful only after using /warcfg pvpinzonesonly:true. This node circumvents the pvp restriction and lets you pvp outside warzones. 
      To setup a pvp world, give war.pvp to players, but only as a permission specific to the pvp world. Other worlds will remain protected
      by the pvpinzonesonly setting. NOTE - No matter what, pvp must be turned on in your server.properties file, otherwise War won't work.
    default: false
commands:
# Player commands
  warzones:
    description: War> Lists the warzones on the server. Each warzone is an independent arena.
    usage: Lists the warzones on the server. Each warzone is an independent arena.
        Ex - /warzones
  zones:
    description: War> Shortcut for /warzones.
    usage: Lists the warzones on the server. Each warzone is an independent arena.
        Ex - /zones
  warzone:
    description: War> Teleports you to the specified warzone's lobby.
    usage: Teleports you to the specified warzone's lobby.
        Ex - /warzone <zone-name>
  zone:
    description: War> Shortcut for /warzone.
    usage: Teleports you to the specified warzone's lobby.
        Ex - /zone <zone-name>
  warhub:
    description: War> Teleports you to the warhub, if it exists. The warhub offers portals to reach each warzone on the server.
    usage: Teleports you to the warhub, if it exists.
        Ex - /warhub
  teams:
    description: War> Lists the teams in the warzone.
    usage: Lists the teams in the warzone. Use zone name when outside warzone.
        Ex - /teams [zone-name]
  join:
    description: War> Use to change teams. Also used instead of walking in the team gate in the lobby.
    usage: Use to change teams. Also used instead of walking in the team gate in the lobby. Must be standing in warzone or lobby.
        Ex - /join <team-color>
  leave:
    description: War> Use to leave a warzone. Teleports you back to the lobby.
    usage: Use to leave a warzone. Teleports you back to the lobby. Must be in team already.
        Ex - /leave
  team:
    description: War> Team chat.
    usage: Team chat.
        Ex - /team <message>
  wstats:
    description: War> Prints the stats in War for a player.
    usage: Lists the stats of a player.
        Ex - /wstats <player>
    aliases: 
        - warstats
        - wstat
# Warzone maker commands (must have the 'war.zonemaker' permission or be added as a zone-maker in /plugins/War/war.txt)
# Battle-related commands
  nextbattle:
    description: War> Warzone blocks are restored, teams are respawned but score remains unaffected. All zone-makers can do this, even if they are not an author of the zone.
    usage: Warzone blocks are restored, teams are respawned but score remains unaffected. All zone-makers can do this, even if they are not an author of the zone. Provide a zone name if not standing in warzone or lobby.
        Ex - /nextbattle [zone-name]
# Warzone creation commands
  setzone:
    description: War> Use to create a warzone. Lobby is created and blocks are saved when the second corner is set. You can only edit zones you create or those listing you as author (add authors with /setzoneconfig author:yourname).
    usage: Use to create a warzone. Lobby is created and blocks are saved when the second corner is set. You can only edit zones you create or those listing you as author (add authors with /setzoneconfig author:yourname). Warzones must be at least 10 blocks wide in all directions.
        \\\\ Wand Cuboid mode \\
        1) /setzone <zone-name> to get wooden sword,
        2) Left-click to select or move corner1,
        3) Right-click to select or move corner2.
        Turn off wand by dropping the wooden sword.
        \\\\ Wandless Cuboid mode \\
        /setzone <zone-name> <corner1/corner2/c1/c2/pos1/pos2>
  savezone:
    description: War> Persists changes made to the warzone since the last save. Config can be set with named parameters.
    usage: Persists changes made to the warzone since the last save. Config can be set with named parameters. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /savezone [zone-name] -> Basic save - name optional if standing inside. \\
        /savezone [zone-name] lifepool:8 teamsize:5 ... -> set warzone configuration options as you save. See /warcfg and /zonecfg for details.
  setzonelobby:
    description: War> Creates or changes the position of the warzone lobby.
    usage: Creates or changes the position of the warzone lobby.
        \\\\ Attached lobby \\
        Must be standing in warzone or lobby.
        /setzonelobby <north/east/south/west/n/e/s/w>
        \\\\ Detached lobby \\
        Must be standing outside warzone or lobby.
        /setzonelobby <zone-name>
  setteam:
    description: War> Creates or moves a team spawn. The lobby is updated.
    usage: Creates or moves a team spawn. The lobby is updated. Must be standing in warzone.
        Ex -
        /setteam <diamond/iron/gold/white/orange/magenta/blue/green/pink/gray/purple/navy/brown/darkgreen/red/black/>
  setmonument:
    description: War> Creates or moves a monument. Monuments can be capture with wool from your team and give your health.
    usage: Creates or moves a monument. Monuments can be capture with wool from your team and give your health. Must be standing in warzone.
        Ex -
        /setmonument <monument-name>
  setteamflag:
    description: War> Creates/moves a team flag post for CTF.
    usage: Creates/moves a team flag post for CTF. Must be standing in warzone.
        Ex -
        /setteamflag <diamond/iron/gold/white/orange/magenta/blue/green/pink/gray/purple/navy/brown/darkgreen/red/black/>
  setbomb:
    description: War> Creates or moves a bomb. Get the bomb to the other team's spawn. People from other teams can blow you up. 
    usage: Creates or moves a bomb. Get the bomb to the other team's spawn. People from other teams can blow you up. Must be standing in warzone.
        Ex -
        /setbomb <bomb-name>
  setcake:
    description: War> Creates or moves a cake. Get the cake to your spawn to score a replenish your lifepool. 
    usage: Creates or moves a bomb. Get the cake to your spawn to score a replenish your lifepool. Must be standing in warzone.
        Ex -
        /setcake <cake-name>   
  resetzone:
    description: War> Reloads zone blocks from disk. Everyone is teleported back to the lobby.
    usage: Reloads zone blocks from disk. Everyone is teleported back to the lobby. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /resetzone [zone-name]
  deletezone:
    description: War> Deletes the zone, resets all blocks.
    usage: Deletes the zone after resetting all blocks. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /deletezone [zone-name]
  renamezone:
    description: War> Renames the zone
    usage: Renames the zone. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /renamezone [zone-name] <new-name>
  deleteteam:
    description: War> Deletes the team. Team must exist.
    usage: Deletes the team. Team must exist. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /deleteteam [zone-name] <team-color>
  deleteteamflag:
    description: War> Deletes the specified team's flag. Team and flag must exist.
    usage: Deletes the specified team's flag. Team and flag must exist. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /deleteteamflag [zone-name] <team-color>
  deletemonument:
    description: War> Deletes the monument.
    usage: Deletes the monument. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /deletemonument [zone-name] <monument-name>
  deletebomb:
    description: War> Deletes the bomb.
    usage: Deletes the bomb. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /deletebomb [zone-name] <bomb-name>
  deletecake:
    description: War> Deletes the cake.
    usage: Deletes the cake. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /deletecake [zone-name] <cake-name>
  zonecfg:
    description: War> Use named parameters to change the configuration of the warzone. May require a /resetzone.
    usage: Use named parameters to change the configuration of the warzone and default team settings. May require a /resetzone. Provide a zone name if not standing in warzone or lobby.
        \\\\ Warzone config \\
        /zonecfg [zone-name] disabled:off -> prevents players from joining. \\
        /zonecfg [zone-name] autoassign:off blockheads:on deathmessages:on friendlyfire:off glasswalls:on instabreak:off 
                             minteams:1 minplayers:1 monumentheal:5 nocreatures:off nodrops:off pvpinzone:on realdeaths:off 
                             resetonempty:off resetonconfigchange:off resetonload:off resetonunload:off unbreakable:off \\
        /zonecfg lobbymaterial:<floor/outline/gate/light> -> while holding block, change the look of the lobby (use air block to keep original floor). \\
        /zonecfg material:<main/stand/light> -> while holding block, change the look of the monument, flag, cake and bomb. 
        \\\\ Team defaults \\
        /zonecfg [zone-name] lifepool:7 -> each death consumes a life from the team's pool, an empty lifepool end the battle and gives a point to the other teams. \\
        /zonecfg maxscore:10 -> once a team reaches this value, the game is ended. \\
        /zonecfg teamsize:10 flagmustbehome:on flagpointsonly:off flagreturn:<both/flag/spawn> nohunger:off respawntimer:0 saturation:10 spawnstyle:<small/flat/big/invisible> \\
        /zonecfg loadout:default -> sets the default respawn inventory to your current items. \\
        /zonecfg loadout:<extra-loadout-name> -> adds an extra loadout (i.e. another player class) that the players can toggle to by sneaking while inside the spawn. \\
        /zonecfg deleteloadout:<extra-loadout-name> -> removes the specified loadout from the choices. \\
        /zonecfg playerloadoutasdefault:true -> the player can bring a copy of his outside-world inventory to fight, it replaces the default loadout. \\
        /zonecfg reward:default -> sets the winner's reward to your current items. 
        \\\\ Print config \\
        /zonecfg [zone-name] print (or /zonecfg -p) -> prints out the warzone settings. \\ 
    aliases: 
        - setzoneconfig
  teamcfg:
    description: War> Use named parameters to change team-specific settings. May require a /resetzone.
    usage: Use named parameters to change the team-specific settings. May require a /resetzone. Provide a zone name if not standing in warzone or lobby.
        \\\\ Team config \\
        /teamcfg [zone-name] <team-name> lifepool:7 -> each death consumes a life from the team's pool, an empty lifepool end the battle and gives a point to the other teams. \\ 
        /teamcfg <team-name> maxscore:10 -> once a team reaches this value, the game is ended. \\
        /teamcfg <team-name> teamsize:10 flagmustbehome:on flagpointsonly:off flagreturn:<both/flag/spawn> nohunger:off respawntimer:0 saturation:10 spawnstyle:<small/flat/big/invisible> \\
        /teamcfg <team-name> loadout:default -> sets the default respawn inventory to your current items. \\
        /teamcfg <team-name> loadout:<extra-loadout-name> -> adds an extra loadout (i.e. another player class) that the players can toggle to by sneaking while inside the spawn. \\ 
        /teamcfg <team-name> deleteloadout:<extra-loadout-name> -> removes the specified loadout from the choices. \\
        /teamcfg <team-name> playerloadoutasdefault:true -> the player can bring a copy of his outside-world inventory to fight, it replaces the default loadout. \\ 
        /teamcfg <team-name> reward:default -> sets the winner's reward to your current items.  
        \\\\ Print config \\
        /teamcfg [zone-name] <team-name> print (or /teamcfg -p) -> prints out the team settings. \\  
    aliases: 
        - setteamconfig
  zonemaker:
    description: War> Toggles between player mode and zone maker mode. Or gives/removes access to zonemaker commands for another player.
    usage: Toggles between player mode and zone maker mode. Or gives/removes access to zonemaker commands for another player.
        Ex -
        /zonemaker
        /zonemaker <new-or-kicked-zone-maker-name>
  zm:
    description: War> Alias for /zonemaker
    usage: Toggles between player mode and zone maker mode. Or gives/removes access to zonemaker commands for another player.
        Ex -
        /zonemaker
        /zonemaker <new-or-kicked-zone-maker-name>
# War admin commands (must have the 'war.*' permission or be an op)
# War hub
  setwarhub:
    description: War> Create or moves a wall of portals. One portal per warzone. Warzones get a portal back to the warhub.
    usage: Create or moves a wall of portals. One portal per warzone. Warzones get a portal back to the warhub.
        Ex -
        /setwarhub
  deletewarhub:
    description: War> Deletes the warhub if it exists. Resets all warzone lobbies.
    usage: Deletes the warhub if it exists. Resets all warzone lobbies.
        Ex -
        /deletewarhub
# Defaults and server configuration
  unloadwar:
    description: War> Disables the War plugin.
    usage: Disables the War plugin.
        Ex -
        /unloadwar
  loadwar:
    description: War> Enables the War plugin.
    usage: Enables the War plugin.
        Ex -
        /loadwar
  warcfg:
    description: War> Change gobal settings and the default warzone configuration values.
    usage: Change global settings and the default warzone and team configuration values.
        \\\\ War config \\
        /warcfg buildinzonesonly:on disablebuildmessage:off -> makes war.build permission required to build outside warzones. \\ 
        /warcfg pvpinzonesonly:on disablepvpmessage:off tntinzonesonly:off -> pvp and tnt denied outside zones (use war.pvp permission to allow pvp). \\
        /warcfg maxzones:12 keepoldzoneversions:on -> manage War's resource usage. \\
        /warcfg warhubmaterial:<floor/outline/gate/light> -> while holding block, change the look of the warhub (use air block to keep original floor). \\
        /warcfg rallypoint:<warzone-name> -> changes game-end teleport destination from lobby to current location - useful for chaining warzones together in a sequence, or preventing players from rejoining immediately. 
        \\\\ Warzone defaults \\
        /warcfg autoassign:off blockheads:on deathmessages:on disabled:off friendlyfire:off glasswalls:on
                instabreak:off minteams:1 minplayers:1 monumentheal:5 nocreatures:off nodrops:off pvpinzone:on
                realdeaths:off resetonempty:off resetonconfigchange:off resetonload:off resetonunload:off unbreakable:off \\
        /warcfg lobbymaterial:<floor/outline/gate/light> -> while holding block, change the look of the lobby (use air block to keep original floor). \\
        /warcfg material:<main/stand/light> -> while holding block, change the look of the monument, flag, cake and bomb. 
        \\\\ Team defaults \\
        /warcfg lifepool:7 -> each death consumes a life from the team's pool, a death with an empty lifepool ends the battle and gives a point to the other teams. \\
        /warcfg maxscore:10 -> once a team reaches this value, the game is ended. \\
        /warcfg teamsize:10 flagmustbehome:on flagpointsonly:off flagreturn:<both/flag/spawn> nohunger:off respawntimer:0 saturation:10 spawnstyle:<small/flat/big/invisible> \\
        /warcfg loadout:default -> sets the default respawn inventory to your current items. \\
        /warcfg loadout:<extra-loadout-name> -> adds an extra loadout (i.e. another player class) that the players can toggle to by sneaking while inside the spawn. \\
        /warcfg deleteloadout:<extra-loadout-name> -> removes the specified loadout from the choices. \\
        /warcfg playerloadoutasdefault:true -> the player can bring a copy of his outside-world inventory to fight, it replaces the default loadout. \\
        /warcfg reward:default -> sets the winner's reward to your current items. 
        \\\\ Print config \\
        /warcfg print (or /warcfg -p) -> prints out the current War settings. \\ 
    aliases: 
        - setwarconfig
# Fallback
  war:
    description: War> Short War help. Can also be used as a prefix for all War commands as a fallback if they conflict with other plugins.
    usage: War is on. Please pick your battle. Try /warhub, /zones and /zone. Further instructions at war.tommytony.com/instructions.
        The /war command can be used as a prefix to all other command as a fallback if they conflict with other plugins. Ex -
        /war,
        /war setzone <zone-name>,
        /war warhub,
        /war zone <zone-name>
  War:
    description: War> Same as /war. Used as fallback.
    usage: See /war.
