name: ${project.name}
version: ${project.version}
api-version: 1.13
description: ${project.description}
author: tommytony
website: ${project.url}
main: com.tommytony.war.War
softdepend: [WorldEdit, Vault]
permissions:
  war.*:
    description: Full War permissions. Create and destroy warzones. Change War configuration.
    default: op
    children:
      war.admin: true
      war.zonemaker: true
      war.player: true
      war.warp: true
      war.build: true
      war.pvp: true
  war.admin:
    description: War admin rights. Create and destroy warzones. Change War configuration.
    default: false
    children:
      war.zonemaker: true
      war.player: true
      war.build: true
  war.zonemaker:
    description: Warzone maker rights. Create and edit warzones, but you can only edit a warzone if you are its author.
    default: false
    children:
      war.player: true
      war.build: true
  war.player:
    description: Lets you participate in War matches.
    default: true
  war.warp:
    description: Gives you access the /zone and /warhub commands that let you teleport to all warzones.
    default: true
  war.build:
    description: 
      Useful only after using /warcfg buildinzonesonly:true. This node circumvents the build restriction and lets you build outside warzones. 
      Give war.build to people that you consider worthy of having build rights. 
    default: false
  war.pvp:
    description: 
      Useful only after using /warcfg pvpinzonesonly:true. This node circumvents the pvp restriction and lets you pvp outside warzones. 
      To setup a pvp world, give war.pvp to players, but only as a permission specific to the pvp world. Other worlds will remain protected
      by the pvpinzonesonly setting. NOTE - No matter what, pvp must be turned on in your server.properties file, otherwise War won't work.
    default: false
commands:
# Player commands
  warzones:
    description: |
      Lists the warzones on the server.
      Each warzone is an independent arena.
    aliases: [zones]
    usage: |
      /<command>
  warzone:
    description: Teleports you to the warzone's lobby.
    aliases: [zone]
    usage: /<command> <zone-name>
  warhub:
    description: Teleports you to the WarHub.
    usage: /<command>
  teams:
    description: |
      Lists the teams in the warzone.
      Use zone name when outside warzone.
    usage: /<command> [zone-name]
  join:
    description: |
      Switch teams during a battle.
      Also used instead of walking in the team gate in the lobby. Must be standing in warzone or lobby.
    usage: /<command> <team-color>
  leave:
    description: |
      Leave a warzone battle.
      Teleports you back to the lobby. Must be in team already.
    usage: /<command>
  team:
    description: Chat with your team.
    usage: |
      /<command> [message]
      Example: /<command> - enable team chat
      Example: /<command> Good game guys - send this message to your team
# Warzone maker commands (must have the 'war.zonemaker' permission or be added as a zone-maker in /plugins/War/war.txt)
# Battle-related commands
  nextbattle:
    description: |
      Respawn all players and blocks.
      Warzone blocks are restored, teams are respawned but score remains unaffected. All zone-makers can do this, even if they are not an author of the zone. Provide a zone name if not standing in warzone or lobby.
    usage: /<command> [zone-name]
# Warzone creation commands
  setzone:
    description: |
      Create a warzone.
      Lobby is created and blocks are saved when the second corner is set. You can only edit zones you create or those listing you as author (add authors with /setzoneconfig author:yourname). Warzones must be at least 10 blocks wide in all directions.
    usage: |
      /<command> <zone-name> [corner1/corner2]
      \\\\ WorldEdit Cuboid mode \\
      1) Create a cuboid selection using WorldEdit
      2) /<command> <zone-name>
      \\\\ Wand Cuboid mode \\
      1) /<command> <zone-name> to get wooden sword,
      2) Left-click to select or move corner1,
      3) Right-click to select or move corner2.
      Turn off wand by dropping the wooden sword.
      \\\\ Wandless Cuboid mode \\
      1) /<command> <zone-name> <corner1/corner2/c1/c2/pos1/pos2>
  savezone:
    description: |
      Save all blocks in a warzone.
      Persists changes made to the warzone since the last save. Config can be set with named parameters. Provide a zone name if not standing in warzone or lobby.
    usage: |
        /<command> [zone-name]
        Example: /<command> [zone-name] - Basic save - name optional if standing inside.
        Example: /<command> [zone-name] lifepool:8 teamsize:5 ... - set warzone configuration options as you save. See /warcfg and /zonecfg for details.
  setzonelobby:
    description: Set the warzone lobby position.
    usage: |
        /<command> [zone-name/north/east/south/west]
        \\\\ Attached lobby \\
        Must be standing in warzone or lobby.
        /setzonelobby <north/east/south/west/n/e/s/w>
        \\\\ Detached lobby \\
        Must be standing outside warzone or lobby.
        /setzonelobby <zone-name>
  setteam:
    description: |
      Create or move a team spawn point.
      The lobby is updated. Must be standing in warzone.
    usage: /<command> <diamond/iron/gold/white/orange/magenta/blue/green/pink/gray/purple/navy/brown/darkgreen/red/black>
  setmonument:
    description: |
      Create or move a monument.
      Monuments can be capture with wool from your team and give your health. Must be standing in warzone.
    usage: /<command> <monument-name>
  setcapturepoint:
    description: |
      Create or move a capture point.
      Capture points build strength and award points. Must be standing in warzone.
    aliases: [setcp]
    usage: /<command> <capture-point-name>
  setteamflag:
    description: |
      Create or move a team's flag.
      Used for CTF. Must be standing in warzone.
    usage: /<command> <team-name>
  setbomb:
    description: |
      Create or move a bomb.
      Get the bomb to the other team's spawn. People from other teams can blow you up. Must be standing in warzone.
    usage: /<command> <bomb-name>
  setcake:
    description: |
      Create or move a cake.
      Get the cake to your spawn to score a replenish your lifepool. Must be standing in warzone.
    usage: /<command> <cake-name>
  resetzone:
    description: |
      Respawn zone blocks and kick players.
      Reloads zone blocks from disk. Everyone is teleported back to the lobby. Provide a zone name if not standing in warzone or lobby.
    usage: /<command> [zone-name]
  deletezone:
    description: |
      Deletes the zone and resets all blocks.
      Provide a zone name if not standing in warzone or lobby.
    usage: /<command> [zone-name]
  renamezone:
    description: |
      Renames the zone.
      Provide a zone name if not standing in warzone or lobby.
    usage: /<command> [zone-name] <new-name>
  deleteteam:
    description: |
      Deletes the team.
      Team must exist. Provide a zone name if not standing in warzone or lobby.
    usage: /<command [zone-name] <team-color>
  deleteteamflag:
    description: |
      Deletes the team's flag.
      Team and flag must exist. Provide a zone name if not standing in warzone or lobby.
    usage: /<command> [zone-name] <team-color>
  deletemonument:
    description: |
      Deletes the monument.
      Provide a zone name if not standing in warzone or lobby.
    usage: /<command> [zone-name] <monument-name>
  deletecapturepoint:
    description: |
      Deletes the capture point.
      Provide a zone name if not standing in warzone or lobby.
    aliases: [deletecp]
    usage: /<command> [zone-name] <capture point name>
  deletebomb:
    description: |
      Deletes the bomb.
      Provide a zone name if not standing in warzone or lobby.
    usage: /<command> [zone-name] <bomb-name>
  deletecake:
    description: |
      Deletes the cake.
      Provide a zone name if not standing in warzone or lobby.
    usage: /<command> [zone-name] <cake-name>
  zonecfg:
    description: |
      Change a warzone's configuration.
      Use named parameters to change the configuration of the warzone and default team settings. May require a /resetzone. Provide a zone name if not standing in warzone or lobby.
    usage: |
        /zonecfg [zone-name] (-p) option:value
        \\\\ Warzone config \\
        /zonecfg [zone-name] disabled:off -> prevents players from joining. \\
        /zonecfg [zone-name] autoassign:off blockheads:on deathmessages:on friendlyfire:off glasswalls:on instabreak:off 
                             minteams:1 minplayers:1 monumentheal:5 nocreatures:off nodrops:off pvpinzone:on realdeaths:off 
                             resetonempty:off resetonconfigchange:off resetonload:off resetonunload:off unbreakable:off \\
        /zonecfg lobbymaterial:<floor/outline/gate/light> -> while holding block, change the look of the lobby (use air block to keep original floor). \\
        /zonecfg material:<main/stand/light> -> while holding block, change the look of the monument, flag, cake and bomb. 
        \\\\ Team defaults \\
        /zonecfg [zone-name] lifepool:7 -> each death consumes a life from the team's pool, an empty lifepool end the battle and gives a point to the other teams. \\
        /zonecfg maxscore:10 -> once a team reaches this value, the game is ended. \\
        /zonecfg teamsize:10 flagmustbehome:on flagpointsonly:off flagreturn:<both/flag/spawn> nohunger:off respawntimer:0 saturation:10 spawnstyle:<small/flat/big/invisible> \\
        /zonecfg loadout:default -> sets the default respawn inventory to your current items. \\
        /zonecfg loadout:<extra-loadout-name> -> adds an extra loadout (i.e. another player class) that the players can toggle to by sneaking while inside the spawn. \\
        /zonecfg loadout:<extra-loadout-name>:<permission> -> add/update a loadout that requires a permission. \\
        /zonecfg deleteloadout:<extra-loadout-name> -> removes the specified loadout from the choices. \\
        /zonecfg playerloadoutasdefault:true -> the player can bring a copy of his outside-world inventory to fight, it replaces the default loadout. \\
        /zonecfg reward:default -> sets the winner's reward to your current items. 
        \\\\ Print config \\
        /zonecfg [zone-name] print (or /zonecfg -p) -> prints out the warzone settings. \\ 
    aliases: 
        - setzoneconfig
  teamcfg:
    description: |
      Change a warzone team's configuration.
      Use named parameters to change the team-specific settings. May require a /resetzone. Provide a zone name if not standing in warzone or lobby.
    usage: |
        /teamcfg [zone-name] <team-name> (-p) option:value
        \\\\ Team config \\
        /teamcfg [zone-name] <team-name> lifepool:7 -> each death consumes a life from the team's pool, an empty lifepool end the battle and gives a point to the other teams. \\ 
        /teamcfg <team-name> maxscore:10 -> once a team reaches this value, the game is ended. \\
        /teamcfg <team-name> teamsize:10 flagmustbehome:on flagpointsonly:off flagreturn:<both/flag/spawn> nohunger:off respawntimer:0 saturation:10 spawnstyle:<small/flat/big/invisible> \\
        /teamcfg <team-name> loadout:default -> sets the default respawn inventory to your current items. \\
        /teamcfg <team-name> loadout:<extra-loadout-name> -> adds an extra loadout (i.e. another player class) that the players can toggle to by sneaking while inside the spawn. \\ 
        /teamcfg <team-name> deleteloadout:<extra-loadout-name> -> removes the specified loadout from the choices. \\
        /teamcfg <team-name> playerloadoutasdefault:true -> the player can bring a copy of his outside-world inventory to fight, it replaces the default loadout. \\ 
        /teamcfg <team-name> reward:default -> sets the winner's reward to your current items.  
        \\\\ Print config \\
        /teamcfg [zone-name] <team-name> print (or /teamcfg -p) -> prints out the team settings. \\  
    aliases: 
        - setteamconfig
  zonemaker:
    description: |
      Change zonemaker status.
      Toggles between player mode and zone maker mode. Or gives/removes access to zonemaker commands for another player.
    alises: [zm]
    usage: |
      /<command> [player-name]
      Example: /<command> - impersonate regular player
      Example: /<command> tommytony - give/revoke zonemaker access from tommytony (does not affect war.x permissions)
# War admin commands (must have the 'war.*' permission or be an op)
# War hub
  setwarhub:
    description: |
      Create or move a wall of portals to warzones.
      One portal per warzone. Warzones get a portal back to the warhub.
    usage: /<command>
  deletewarhub:
    description: |
      Deletes the WarHub.
      Resets all warzone lobbies.
    usage: /<command>
# Defaults and server configuration
  unloadwar:
    description: Disables the War plugin.
    usage: /<command>
  loadwar:
    description: Enables the War plugin.
    usage: /<command>
  warcfg:
    description: |
      Change War global settings.
      Change global settings and the default warzone and team configuration values.
    usage: |
        /warcfg (-p) option:value
        \\\\ War config \\
        /warcfg buildinzonesonly:on disablebuildmessage:off -> makes war.build permission required to build outside warzones. \\ 
        /warcfg pvpinzonesonly:on disablepvpmessage:off tntinzonesonly:off -> pvp and tnt denied outside zones (use war.pvp permission to allow pvp). \\
        /warcfg maxzones:12 keepoldzoneversions:on -> manage War's resource usage. \\
        /warcfg warhubmaterial:<floor/outline/gate/light> -> while holding block, change the look of the warhub (use air block to keep original floor). \\
        /warcfg rallypoint:<warzone-name> -> changes game-end teleport destination from lobby to current location - useful for chaining warzones together in a sequence, or preventing players from rejoining immediately. 
        \\\\ Warzone defaults \\
        /warcfg autoassign:off blockheads:on deathmessages:on disabled:off friendlyfire:off glasswalls:on
                instabreak:off minteams:1 minplayers:1 monumentheal:5 nocreatures:off nodrops:off pvpinzone:on
                realdeaths:off resetonempty:off resetonconfigchange:off resetonload:off resetonunload:off unbreakable:off souphealing:on\\
        /warcfg lobbymaterial:<floor/outline/gate/light> -> while holding block, change the look of the lobby (use air block to keep original floor). \\
        /warcfg material:<main/stand/light> -> while holding block, change the look of the monument, flag, cake and bomb. 
        \\\\ Team defaults \\
        /warcfg lifepool:7 -> each death consumes a life from the team's pool, a death with an empty lifepool ends the battle and gives a point to the other teams. \\
        /warcfg maxscore:10 -> once a team reaches this value, the game is ended. \\
        /warcfg teamsize:10 flagmustbehome:on flagpointsonly:off flagreturn:<both/flag/spawn> nohunger:off respawntimer:0 saturation:10 spawnstyle:<small/flat/big/invisible> \\
        /warcfg loadout:default -> sets the default respawn inventory to your current items. \\
        /warcfg loadout:<extra-loadout-name> -> adds an extra loadout (i.e. another player class) that the players can toggle to by sneaking while inside the spawn. \\
        /warcfg deleteloadout:<extra-loadout-name> -> removes the specified loadout from the choices. \\
        /warcfg playerloadoutasdefault:true -> the player can bring a copy of his outside-world inventory to fight, it replaces the default loadout. \\
        /warcfg reward:default -> sets the winner's reward to your current items. 
        \\\\ Print config \\
        /warcfg print (or /warcfg -p) -> prints out the current War settings. \\ 
    aliases: 
        - setwarconfig
# Fallback
  war:
    description: |
      Open the War UI.
      War is on. Please pick your battle. Try /warhub, /zones and /zone. Further instructions at https://github.com/taoneill/war/wiki
      The /war command can be used as a prefix to all other command as a fallback if they conflict with other plugins.
    aliases: [War]
    usage: |
      /<command>
      The War UI can also be opened by left-clicking with a item of TNT that has been renamed to War.
      Command fallback examples:
      /<command> zone <zone-name> - teleport to a warzone
      /<command> leave - leave a zone
