name: War
version: 1.6.1 (de Gaulle)
description: Lets you create TDM and CTF arenas (warzones) for a fast-paced and structured PVP experience.
author: tommytony
website: war.tommytony.com
main: bukkit.tommytony.war.War
permissions:
  war.*:
    description: Full War permissions. Create and destroy warzones. Change War configuration.
    default: op
    children:
      war.admin: true
      war.zonemaker: true
      war.player: true
      war.warp: true
      war.build: true
      war.pvp: true
  war.admin:
    description: War admin rights. Create and destroy warzones. Change War configuration.
    default: false
    children:
      war.zonemaker: true
      war.player: true
      war.build: true
  war.zonemaker:
    description: Warzone maker rights. Create and edit warzones, but you can only edit a warzone if you are its author.
    default: false
    children:
      war.player: true
      war.build: true
  war.player:
    description: Lets you participate in War matches.
    default: true
  war.warp:
    description: Gives you access the /zone and /warhub commands that let you teleport to all warzones.
    default: true
  war.build:
    description: 
      Useful only after using /warcfg buildinzonesonly:true. This node circumvents the build restriction and lets you build outside warzones. 
      Give war.build to people that you consider worthy of having build rights. 
    default: false
  war.pvp:
    description: 
      Useful only after using /warcfg pvpinzonesonly:true. This node circumvents the pvp restriction and lets you pvp outside warzones. 
      To setup a pvp world, give war.pvp to players, but only as a permission specific to the pvp world. Other worlds will remain protected
      by the pvpinzonesonly setting. NOTE - No matter what, pvp must be turned on in your server.properties file, otherwise War won't work.
    default: false
commands:
# Player commands
  warzones:
    description: War> Lists the warzones on the server. Each warzone is an independent arena.
    usage: Lists the warzones on the server. Each warzone is an independent arena.
        Ex - /warzones
  zones:
    description: War> Shortcut for /warzones.
    usage: Lists the warzones on the server. Each warzone is an independent arena.
        Ex - /zones
  warzone:
    description: War> Teleports you to the specified warzone's lobby.
    usage: Teleports you to the specified warzone's lobby.
        Ex - /warzone <zone-name>
  zone:
    description: War> Shortcut for /warzone.
    usage: Teleports you to the specified warzone's lobby.
        Ex - /zone <zone-name>
  warhub:
    description: War> Teleports you to the warhub, if it exists. The warhub offers portals to reach each warzone on the server.
    usage: Teleports you to the warhub, if it exists.
        Ex - /warhub
  teams:
    description: War> Lists the teams in the warzone.
    usage: Lists the teams in the warzone. Use zone name when outside warzone.
        Ex - /teams [zone-name]
  join:
    description: War> Use to change teams. Also used instead of walking in the team gate in the lobby.
    usage: Use to change teams. Also used instead of walking in the team gate in the lobby. Must be standing in warzone or lobby.
        Ex - /join <team-color>
  leave:
    description: War> Use to leave a warzone. Teleports you back to the lobby.
    usage: Use to leave a warzone. Teleports you back to the lobby. Must be in team already.
        Ex - /leave
  team:
    description: War> Team chat.
    usage: Team chat.
        Ex - /team <message>
# Warzone maker commands (must have the 'war.zonemaker' permission or be added as a zone-maker in /plugins/War/war.txt)
# Battle-related commands
  nextbattle:
    description: War> Warzone blocks are restored, teams are respawned but score remains unaffected. All zone-makers can do this, even if they are not an author of the zone.
    usage: Warzone blocks are restored, teams are respawned but score remains unaffected. All zone-makers can do this, even if they are not an author of the zone. Provide a zone name if not standing in warzone or lobby.
        Ex - /nextbattle [zone-name]
# Warzone creation commands
  setzone:
    description: War> Use to create a warzone. Lobby is created and blocks are saved when the second corner is set. You can only edit zones you create or those listing you as author (add authors with /zonecfg author:yourname).
    usage: Use to create a warzone. Lobby is created and blocks are saved when the second corner is set. You can only edit zones you create or those listing you as author (add authors with /zonecfg author:yourname). Warzones must be at least 10 blocks wide in all directions.
        Ex -
        ==Wand Cuboid mode==>
        1) /setzone <zone-name> to get wooden sword,
        2) Left-click to select or move corner1,
        3) Right-click to select or move corner2.
        Turn off wand by dropping the wooden sword.
        ==Wandless Cuboid mode==>
        /setzone <zone-name> <corner1/corner2/c1/c2/pos1/pos2>
  savezone:
    description: War> Persists changes made to the warzone since the last save. Config can be set with named parameters.
    usage: Persists changes made to the warzone since the last save. Config can be set with named parameters. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /savezone [zone-name] => Basic save - name optional if standing inside,
        /savezone [zone-name] lifepool:8 teamsize:5 maxscore:7 autoassign:on ff:on blockheads:on spawnstyle:<big/flat/small/invisible> unbreakable:on nocreatures:on disabled:on monumentheal:<0-20>
                              flagreturn:<both/spawn/flag> flagpointsonly:false glasswalls:on pvpinzone:true instabreak:false nodrops:false nohunger:false saturation:<0-20> minplayers:1 minteams:1 
        /savezone [zone-name] loadout:default => sets the respawn inventory to your current items,
        /savezone [zone-name] loadout:<extra-loadout-name> => adds an extra loadout (i.e. another player class) that the players can toggle to by sneaking while inside the spawn
        /savezone [zone-name] deleteloadout:<extra-loadout-name> => removed the specified loadout from the choices. You cannot remove the default loadout.
        /savezone [zone-name] reward:default => sets the winner's reward to your current items.
        /savezone [zone-name] author:tommytony,someguy => adds these players as authors of the warzone, allowing them to edit it.
        /savezone [zone-name] deleteauthor:tommytony,someguy => removes these players from the warzone authors.
  setzonelobby:
    description: War> Creates or changes the position of the warzone lobby.
    usage: Creates or changes the position of the warzone lobby.
        Ex -
        ==Attached lobby==>
        Must be standing in warzone or lobby.
        /setzonelobby <north/east/south/west/n/e/s/w>
        ==Detached lobby==>
        Must be standing outside warzone or lobby.
        /setzonelobby <zone-name>
  setteam:
    description: War> Creates or moves a team spawn. The lobby is updated.
    usage: Creates or moves a team spawn. The lobby is updated. Must be standing in warzone.
        Ex -
        /setteam <diamond/iron/gold/white/orange/magenta/blue/green/pink/gray/purple/navy/brown/darkgreen/red/black>
  setmonument:
    description: War> Creates or moves a monument.
    usage: Creates or moves a monument. Must be standing in warzone.
        Ex -
        /setmonument <monument-name>
  setteamflag:
    description: War> Creates/moves a team flag post for CTF.
    usage: Creates/moves a team flag post for CTF. Must be standing in warzone.
        Ex -
        /setteamflag <team-color>
  resetzone:
    description: War> Reloads zone blocks from disk. Everyone is teleported back to the lobby.
    usage: Reloads zone blocks from disk. Everyone is teleported back to the lobby. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /resetzone [zone-name]
  deletezone:
    description: War> Deletes the zone, resets all blocks.
    usage: Deletes the zone after resetting all blocks. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /deletezone [zone-name]
  renamezone:
    description: War> Renames the zone
    usage: Renames the zone. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /renamezone [zone-name] <new-name>
  deleteteam:
    description: War> Deletes the team. Team must exist.
    usage: Deletes the team. Team must exist. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /deleteteam [zone-name] <team-color>
  deleteteamflag:
    description: War> Deletes the specified team's flag. Team and flag must exist.
    usage: Deletes the specified team's flag. Team and flag must exist. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /deleteteamflag [zone-name] <team-color>
  deletemonument:
    description: War> Deletes the monument.
    usage: Deletes the monument. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /deletemonument [zone-name] <monument-name>
  setzoneconfig:
    description: War> Use named parameters to change the configuration of the warzone. Resets blocks like /nextbattle. Does not save zone blocks like /savezone.
    usage: Use named parameters to change the configuration of the warzone. Resets blocks like /nextbattle. Does not save zone blocks like /savezone. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /setzoneconfig [zone-name] lifepool:8 teamsize:5 maxscore:7 autoassign:on ff:on blockheads:on spawnstyle:<big/flat/small/invisible> unbreakable:on nocreatures:on disabled:on monumentheal:<0-20>
                                   flagreturn:<both/spawn/flag> flagpointsonly:false glasswalls:on pvpinzone:true instabreak:false nodrops:false nohunger:false saturation:<0-20> minplayers:1 minteams:1
        /setzoneconfig [zone-name] loadout:default => sets the respawn inventory to your current items,
        /setzoneconfig [zone-name] loadout:<extra-loadout-name> => adds an extra loadout (i.e. another player class) that the players can toggle to by sneaking while inside the spawn
        /setzoneconfig [zone-name] deleteloadout:<extra-loadout-name> => removed teh specified loadout from the choices. You cannot remove the default loadout.
        /setzoneconfig [zone-name] reward:default => sets the winner's reward to your current items.
        /setzoneconfig [zone-name] author:tommytony,someguy => adds these players as authors of the warzone, allowing them to edit it.
        /setzoneconfig [zone-name] deleteauthor:tommytony,someguy => removes these players from the warzone authors.
  zonecfg:
    description: War> Alias for /setzoneconfig
    usage: Use named parameters to change the configuration of the warzone. Resets blocks like /nextbattle. Does not save zone blocks like /savezone. Provide a zone name if not standing in warzone or lobby.
        Ex -
        /zonecfg [zone-name] lifepool:8 teamsize:5 maxscore:7 autoassign:on ff:on blockheads:on spawnstyle:<big/flat/small/invisible> unbreakable:on nocreatures:on disabled:on monumentheal:<0-20>
                             flagreturn:<both/spawn/flag> flagpointsonly:false glasswalls:on pvpinzone:true instabreak:false nodrops:false nohunger:false saturation:<0-20> minplayers:1 minteams:1
        /zonecfg [zone-name] loadout:default => sets the respawn inventory to your current items,
        /zonecfg [zone-name] loadout:<extra-loadout-name> => adds an extra loadout (i.e. another player class) that the players can toggle to by sneaking while inside the spawn
        /zonecfg [zone-name] deleteloadout:<extra-loadout-name> => removed teh specified loadout from the choices. You cannot remove the default loadout.
        /zonecfg [zone-name] reward:default => sets the winner's reward to your current items.
        /zonecfg [zone-name] author:tommytony,someguy => adds these players as authors of the warzone, allowing them to edit it.
        /zonecfg [zone-name] deleteauthor:tommytony,someguy => removes these players from the warzone authors.
  zonemaker:
    description: War> Toggles between player mode and zone maker mode. Or gives/removes access to zonemaker commands for another player.
    usage: Toggles between player mode and zone maker mode. Or gives/removes access to zonemaker commands for another player.
        Ex -
        /zonemaker
        /zonemaker <new-or-kicked-zone-maker-name>
  zm:
    description: War> Alias for /zonemaker
    usage: Toggles between player mode and zone maker mode. Or gives/removes access to zonemaker commands for another player.
        Ex -
        /zonemaker
        /zonemaker <new-or-kicked-zone-maker-name>
# War admin commands (must have the 'war.*' permission or be an op)
# War hub
  setwarhub:
    description: War> Create or moves a wall of portals. One portal per warzone. Warzones get a portal back to the warhub.
    usage: Create or moves a wall of portals. One portal per warzone. Warzones get a portal back to the warhub.
        Ex -
        /setwarhub
  deletewarhub:
    description: War> Deletes the warhub if it exists. Resets all warzone lobbies.
    usage: Deletes the warhub if it exists. Resets all warzone lobbies.
        Ex -
        /deletewarhub
# Defaults and server configuration
  unloadwar:
    description: War> Disables the War plugin.
    usage: Disables the War plugin.
        Ex -
        /unloadwar
  loadwar:
    description: War> Enables the War plugin.
    usage: Enables the War plugin.
        Ex -
        /loadwar
  setwarconfig:
    description: War> Change gobal settings and the default warzone configuration values.
    usage: Change gobal settings and the default warzone configuration values.
        Ex -
        /setwarconfig pvpinzonesonly:on buildinzonesonly:on disablepvpmessage:off tntinzonesonly:off maxzones:12 => Global settings,
        /setwarconfig lifepool:8 teamsize:5 maxscore:7 autoassign:on ff:on blockheads:on spawnstyle:<big/flat/small/invisible> unbreakable:on nocreatures:on disabled:on monumentheal:<0-20>
                      flagreturn:<both/spawn/flag> flagpointsonly:false glasswalls:on pvpinzone:true instabreak:false nodrops:false nohunger:false saturation:<0-20> minplayers:1 minteams:1
                      =>  Warzone defaults,
        /setwarconfig loadout:default => sets the respawn inventory to your current items,
        /setwarconfig loadout:<extra-loadout-name> => adds an extra loadout (i.e. another player class) that the players can toggle to by sneaking while inside the spawn
        /setwarconfig deleteloadout:<extra-loadout-name> => removed teh specified loadout from the choices. You cannot remove the default loadout.
        /setwarconfig reward:default => sets the winner's reward to your current items.
        /setwarconfig rallypoint:<warzone-name>  =>  changes when players get teleported at the end of a match for that zone, useful for chaining warzones together in a sequence, or preventing players from rejoining immediately
  warcfg:
    description: War> Alias for /setwarconfig
    usage: Change gobal settings and the default warzone configuration values.
        Ex -
        /warcfg pvpinzonesonly:on buildinzonesonly:on disablepvpmessage:off tntinzonesonly:off maxzones:12 => Global settings,
        /warcfg lifepool:8 teamsize:5 maxscore:7 autoassign:on ff:on blockheads:on spawnstyle:<big/flat/small/invisible> unbreakable:on nocreatures:on disabled:on monumentheal:<0-20>
                flagreturn:<both/spawn/flag> flagpointsonly:false glasswalls:on pvpinzone:true instabreak:false nodrops:false nohunger:false saturation:<0-20> minplayers:1 minteams:1
                =>  Warzone defaults,
        /warcfg loadout:default => sets the respawn inventory to your current items,
        /warcfg loadout:<extra-loadout-name> => adds an extra loadout (i.e. another player class) that the players can toggle to by sneaking while inside the spawn
        /warcfg deleteloadout:<extra-loadout-name> => removed teh specified loadout from the choices. You cannot remove the default loadout.
        /warcfg reward:default => sets the winner's reward to your current items.
        /warcfg rallypoint:<warzone-name>  =>  changes when players get teleported at the end of a match for that zone, useful for chaining warzones together in a sequence, or preventing players from rejoining immediately
# Fallback
  war:
    description: War> Short War help. Can also be used as a prefix for all War commands as a fallback if they conflict with other plugins.
    usage: War is on. Please pick your battle. Try /warhub, /zones and /zone. Further instructions at war.tommytony.com/instructions.
        The /war command can be used as a prefix to all other command as a fallback if they conflict with other plugins. Ex -
        /war,
        /war setzone <zone-name>,
        /war warhub,
        /war zone <zone-name>
  War:
    description: War> Same as /war. Used as fallback.
    usage: See /war.